# Main dataset path
data:
  raw_path: data/winequality-red.csv
  processed_path: data/processed
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv

# Preprocessing parameters
preprocess:
  target_col: quality # The column we want to predict

# Training parameters
training:
  test_size: 0.2
  random_state: 42

# Model selection and hyperparameters
# Options: random_forest, logistic_regression
model:
  name: logistic_regression # Change this to 'logistic_regression' to switch models
  
  # Parameters for RandomForestClassifier
  random_forest:
    n_estimators: 300
    max_depth: 5
    random_state: 42
    
  # Parameters for LogisticRegression
  logistic_regression:
    C: 0.1
    solver: 'liblinear'
    random_state: 42

# Evaluation output paths
evaluate:
  model_path: models/model.pkl
  metrics_path: metrics/metrics.json
  plots_path: plots/